[[section-solution-strategy]]
== Solution Strategy




=== Technology decisions
[cols=2*,options="header"]
|===
|Tecnología
|Descripción

|Git
|Sistema de control de versiones de software.

|GitHub
|Servicio basado en la nube que aloja al sistema de control de versiones antes mencionado, Git.

|Solid
|Especificación que permite almacenar datos de forma segura en almacenes descentralizados de datos denominados Pods.

|Node.js
|Entorno de ejecución para JavaScript empleado para desarrollar aplicaciones escalables del lado del servidor.

|Express
|Framework para la construcción de aplicaciones web en Node.js.

|TypeScript
|Lenguaje de programación construido a un nivel superior de JavaScript que ofrece una mayor seguridad, escalabilidad y limpieza en el código.

|React
|Biblioteca de JavaScript que nos permite creear interfaces de usuario interactivas de manera sencilla. Se basa en componentes.

|Leaflet
|Biblioteca de mapas, open-source y basada en OpenStreetMaps.

|Docker
|Docker es una herramienta que facilita la creación, implementación y ejecución de aplicaciones mediante el uso de contenedores. Los contenedores permiten empaquetar una aplicación con todas las partes que necesita, como bibliotecas y otras dependencias, y desplegarla como un solo paquete.

|Firebase Cloud Storage
|Servicio empleado para almacenar contenido generado por los usuarios, por ejemplo, imágenes y vídeos.

|Jest
|Framework de pruebas para JavaScript. 

|Puppeteer
|Herramienta de automatización de pruebas para navegadores web desarrollada por Google. Permite controlar el navegador a través de una API.

|Cucumber
|Herramienta de automatización de pruebas de software empleada para realizar pruebas a partir de los criterios de aceptación. A través de Cucumber, se pueden definir un conjunto de casos de uso que permiten validar el desarrollo realizado.
|===


=== Decisions on how to achieve quality goals
- Usabilidad: el equipo se preocupará de diseñar una interfaz clara y accesible para cualquier usuario. Para ello nos basaremos en los estándares de usabilidad en la web.
- Privacidad: la información privada del usuario se almacenará en pods de SOLID, manteniéndola, de este modo, descentralizada. Sólo se almacenará en una base de datos centralizada lo estrictamente necesario.
- Seguridad: nos preocuparemos de implementar todas las medidas que consideremos oportunas para securizar nuestra aplicación. Además, el mantener la información personal de los usuarios descentralizada constituye un gran paso en el proceso.
- Testabilidad: es un objetivo de calidad importante para garantizar que el software sea confiable, robusto y libre de errores. Es importante implementar prácticas de desarrollo de software adecuadas, como la separación de preocupaciones y el diseño modular.

=== Relevant organizational decisions
En cuanto a la organización dentro del equipo, hemos tomado las siguientes decisiones:

- Las reuniones extraordinarias, las hacemos a través de Discord, por estar todos los miembros del equipo familiarizados con dicha herramienta.
- La comunicación entre los miembros del equipo se produce, principalmente, a través de un grupo de WhatsApp, pero cualquier problema que surja también se refleja como una issue en Github.
- Empleamos un tablero Kanban dentro de github para tener bien organizadas y de forma muy clara las tareas que tiene que realizar/está realizando cada miembro del equipo.