[[section-building-block-view]]


== Building Block View

=== Level 0: Whitebox of the Overall System 

[plantuml, "whitebox-overall-system", png]
----
actor Usuario
Component LoMap
Component pod as "Inrupt/Proveedor POD"

Usuario -right-> LoMap: interactúa

LoMap <-right-> pod: obtiene datos Usuario
----

Motivation::
LoMap es la estructura principal de un sistema en el que el usuario interactúa con su mapa, personalizándolo con los lugares que le interesan.
La información personal del usuario se almacena de forma descentralizada en PODs.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| Usuario | Interactúa con la aplicación.
| LoMap | Sistema con el que interactúa el usuario. Se comunica con el proveedor de PODs para obtener la información necesaria del usuario.
| Inrupt/Proveedor POD | Sistema encargado de almacenar la información de cada usuario en un POD de forma descentralizada.
|===

=== Level 1

[plantuml, "level-2", png]
----
actor Usuario
Component LoMap {
  Component web as "WebApp"
  Component api as "RestAPI"
}
Database db as "MongoDB"
Component pod as "Inrupt"

Usuario -right-> web: interactua
web <-right-> api: envia peticiones
api <-down-> db: almacena/recupera datos

LoMap <-down-> pod: obtiene datos
----

Motivation::
Muestra como funcionan los distintos componentes de LoMap, a grandes rasgos.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| WebApp | Parte del sistema con la que interactúa el usuario (Frontend).
| ResAPI | Parte del sistema encargada de llevar a cabo las acciones indicadas por el usuario. Se comunica con la WebApp y con MongoDB (Backend). 
| MongoDB | Base de datos empleada para almacenar la información no personal de los usuarios.
|===

