[[section-building-block-view]]


== Building Block View

=== Level 0: Whitebox of the Overall System 

[plantuml, "whitebox-overall-system", png]
----
actor Usuario
Component LoMap
Component pod as "POD"

Usuario -right-> LoMap: interactúa
Usuario -right-> pod: tiene
LoMap <-right-> pod: obtiene/almacena datos Usuario
----

Motivation::
LoMap es la estructura principal de un sistema en el que el usuario interactúa con su mapa, personalizándolo con los lugares que le interesan. 
Además, el usuario puede añadir a sus amigos a la aplicación y compartir con ellos sus marcadores.
La información personal del usuario se almacena de forma descentralizada en PODs.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| Usuario | Interactúa con la aplicación.
| LoMap | Sistema con el que interactúa el usuario. Se comunica con el proveedor de PODs para obtener/almacenar información del usuario.
| POD | Proveedor encargado de almacenar la información de cada usuario en un POD de forma descentralizada.
|===

=== Level 1

[plantuml, "level-1", png]
----
actor Usuario
Component LoMap {
  Component web as "WebApp"
}
Component pod as "POD"

Usuario -right-> web: interactua
Usuario -right-> pod: tiene

web <-down-> pod: obtiene/almacena datos
----

Motivation::
Muestra como funcionan los distintos componentes de LoMap, a grandes rasgos.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| WebApp | Parte del sistema con la que interactúa el usuario (Frontend). Además, es la parte encargada de comunicarse con los pods de los usuarios.
|===

=== Level 2
[plantuml, "level-2", png]

----
left to right direction

actor user as "Usuario"

Component web as "WebApp" {  
  Component login as "LoginPage"
  Component home as "HomePage"
  Component about as "AboutPage"
  Component create as "CreatePointPage"
  Component single as "SinglePointDetailsPage"
  Component saved as "SavedPointsPage"      
}   


Database pod as "POD"


login <-left- user: se logea
login -down-> home: se redirige a
home -left-> saved: accede a
home -down-> single: accede a
home -right-> about: accede a
home -down-> create: accede a
user -down-> pod: almacena/recupera datos
----

Motivation::
Muestra como funcionan los distintos componentes de LoMap, con mas detalle que el nivel anterior. Se profundiza en los distintos componentes de la aplicación que forman parte de WebApp.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| LoginPage | Parte del sistema encargada de redirigir al usuario al proveedor Solid seleccionado para llevar a cabo su autenticación.
| HomePage | Muestra un mapa en el que se sitúan los puntos almacenados del usuario, así como los compartidos por sus amigos, si así lo desea. Permite filtrar los puntos a mostrar por su categoría. Además, permite acceder a cualquier parte de la aplicación.
| CreatePointPage | Permite al usuario en sesión crear un nuevo punto y compartirlo con sus amigos, si así lo desea.
| AboutPage | Muestra al usuario de la aplicación información acerca de ésta.
| SavedPointsPage | Permite al usuario interactuar con los puntos que ha decidido guardar.
| SinglePointDetailsPage | Permite al usuario ver en detalle toda la información almacenada acerca de un punto dado. También permite ver en detalle toda la información de puntos que les han compartido sus amigos.
|===


