[[section-runtime-view]]
== Runtime View

=== Runtime Level 1

==== Inicio de sesión

El inicio de sesión de la aplicación se gestiona a través del proveedor de SOLID Inrupt, que se encarga de almacenar las credenciales e información privada del usuario.
El usuario se comunica con el sistema Lomap y accede a su POD personal. Al introducir el webId en el formulario, se redirecciona al proveedor Inrupt para su autenticación y, si los datos son verídicos, se redirecciona a lomap, mostrando en una vista de la aplicación el mapa con los puntos de interés añadidos (y que el usuario en sesión tenga permiso para ver).

[plantuml, "runtime-6-1-1", svg]

----
actor Usuario
participant lomap as "Sistema Lomap"
database Pod as "Pod personal"
Usuario -> lomap: Introducir credenciales
lomap -> Pod: Recuperar datos
Pod --> lomap: Redirección a vista 
lomap --> Usuario: Interacción visual
----

==== Listado de puntos de interés de un usuario
Los puntos de interés se almacenan en el pod personal de cada usuario. El sistema lomap se encarga de recuperar los datos del pod personal del usuario y mostrarlos en la vista correspondiente. El usuario puede interactuar con la vista y acceder a la información de cada punto de interés.

[plantuml, "runtime-6-1-2", svg]
----
actor Usuario
participant lomap as "Sistema Lomap"
database Pod as "Pod personal"
activate lomap
Usuario -> lomap: Acceder a vista
lomap -> Pod: getPoints()
Pod --> lomap: Redirección a vista
lomap --> Usuario: Interacción visual
deactivate lomap
----

==== Añadir un punto de interés al mapa
Para añadir un punto de interés al mapa, el usuario tendrá varias opciones. A continuación, se explicará la opción más "compleja". El usuario interactúa dentro de su vista privada y accede a una opción que le redirecciona a una vista específica para añadir un nuevo punto al mapa. La vista de añadir nuevo punto contiene un formulario, a través del cual se envían los datos al sistema lomap, que se encarga de comunicar con el pod personal del usuario y actualizar la interfaz de usuario.

[plantuml, "runtime-6-1-3", svg]
----
actor Usuario
participant lomap as "Sistema Lomap"
database pod as "Pod personal"

Usuario -> lomap: redirectToPointViewPage()
activate lomap
lomap -> lomap: validarDatos()
lomap -> pod: storeNewPoint()
pod --> lomap: success
lomap -> lomap: Actualizar componente mapa
lomap --> Usuario: Mostrar vista actualizada

deactivate lomap
----


=== Runtime Level 2

==== Inicio de sesión
Para iniciar sesión, el usuario introducirá su webId en el formulario. El proveedor de PODs recibe el webId y procesa la petición. Redirecciona a la página privada del usuario y, a su vez, los datos del POD de éste. Si se produce un error al realizar la petición, se mostrará un error en el formulario de la página de inicio de sesión. En caso de producirse un error en el proveedor (Por otros motivos inherentes a él), se gestionará el error redireccionando de nuevo al formulario.

[plantuml,"runtime-6-2-1",svg]
----
actor Usuario
participant personal as "Vista Home"
participant form as "Formulario login"
participant Api as "API cliente"
database Pod as "Pod personal"
Usuario -> form: Rellenar formulario

activate Api
form -> Api: iniciar sesión
Api -> Api: Validar webId
Api -> Pod: iniciar sesión
Pod -> Pod: Comprobar webId
Pod --> Api: Enviar datos Pod
Api --> form: Enviar datos pod
deactivate Api

form --> personal: Redireccionar a página de inicio
----

==== Listado de puntos de un usuario
El listado de puntos de interés de un usuario se obtiene del pod del usuario. Sin embargo, el sistema lomap se encarga de gestionar la petición y mostrar los datos en la vista correspondiente. El usuario puede interactuar con la vista y acceder a la información de cada punto de interés. El fichero JSON devuelto por el POD tiene que ser procesado para mostrar los datos en la vista.

[plantuml,"runtime-6-2-2", svg]
----
actor Usuario
participant inicio as "Vista Home"
participant Api as "Api cliente"
participant parser as "Parser"
database Pod as "Pod personal"

Usuario -> inicio: Acceder a vista

activate Api
inicio -> Api: findAllPointsFromCurrentUser()
Api -> Pod: Recuperar datos
Pod --> Api: Enviar datos en .json
Api -> parser: Parsear datos
parser --> Api: Enviar datos (Tipo Point)
Api --> inicio: Mostrar datos
deactivate Api

----

==== Añadir un punto de interés en el mapa
Para añadir un punto de interés en el mapa se contemplan varias opciones. El siguiente diagrama representa el escenario de añadir un punto de interés desde la vista privada del usuario (Dashboard).

[plantuml,"runtime-6-2-3", svg]
----
actor Usuario
participant personal as "Vista privada"
participant home as "Vista inicio"
participant Api as "Api Cliente"
participant parser as "Parser"
box "Servicio de Inrupt" #wheat
database pod as "Pod personal"
end box
database firebase as "Firebase Storage"

Usuario -> personal: 
activate Api
personal -> Api: crear punto interés 
Api -> Api: Validar datos

activate parser
Api -> parser: Parsear datos
parser --> Api: Enviar datos (Tipo Point)
deactivate parser

Api -> firebase: <<async>>Almacenar imagen del punto
firebase --> Api: Respuesta
Api -> pod: Almacenar datos
pod --> Api: Enviar datos
Api --> home: Enviar datos
deactivate Api

activate home
home -> home: actualizar datos del mapa
home --> Usuario: Mostrar mensaje
deactivate home
----

=== Runtime Level 3

==== Inicio de sesión
[plantuml,"runtime-6-3-1", svg]
----
actor Usuario
participant personal as "Vista Home"
participant form as "Formulario login"
participant Api as "API Cliente"

box "Servicio de Inrupt" #wheat
database Pod as "Pod personal"
end box

Usuario -> form: Introducir webId
form -> Api: iniciar sesión

activate Api
Api -> Api: Validar webId
Api -> Pod: iniciar sesión
deactivate Api

activate Pod
Pod -> Pod: Comprobar webId
Pod --> Api: Enviar datos Pod
deactivate Pod

activate Api
Api --> personal: Enviar datos pod
deactivate Api

----

==== Listado de puntos de interés de un usuario
[plantuml,"runtime-6-3-2", svg]
----
actor Usuario
participant personal as "Vista Personal"
participant api as "API Cliente"
participant servicio as "Servicio"
participant parser as "JSON Parser"

box "Servicio de Inrupt" #wheat
database pod as "Pod personal"
end box

Usuario -> personal: Acceder a vista
activate api
personal -> api: findAllPointsFromCurrentUser()
api -> api: Comprobar usuario en sesión
api -> servicio: Recuperar datos

activate servicio
activate pod
servicio -> pod: obtener JSON de puntos
pod --> servicio: Enviar datos en .json
deactivate pod

activate parser
servicio -> parser: Parsear datos
parser --> servicio: Enviar datos (Tipo Point)
note right
Los datos se parsean de JSON a un objeto Point
end note
deactivate parser 

servicio --> api: Enviar array de puntos (Tipo Point)

deactivate servicio

api --> personal: Mostrar puntos en la vista
deactivate api

personal --> Usuario: actualizar vista

----

==== Añadir un punto de interés en el mapa
[plantuml,"runtime-6-3-3", svg]
----
actor Usuario
participant Personal as ":Vista Home"
participant PointView as ":Vista añadir punto de interés"
participant Home as ":Vista Inicio"

box "api" #Moccasin
participant Api as ":Api Cliente"
participant Service as ":PointService"
end box

participant parser as ":JSON Parser"
participant util as ":JSON Utils"

box "Database" #LightBlue
database firebase as ":Firebase Storage"
end box

box "Proveedor POD" #PapayaWhip
database pod as ":POD personal"
end box

Usuario -> Personal: 
Personal -> PointView: redirectToPointView()
note left
Redireccionar a una vista exclusiva
para añadir el nuevo punto de interés
end note
activate PointView
PointView -> Api: handleOnClick() 
activate Personal
Api -> Api: Validar datos
activate Api
Api --> Personal

Api -> Service: addNewPoint()
activate Service
Service -> Service: checkParams()
Service --> Api: sendParamErrors()
note left: Comprobación parámetros punto

activate firebase

Service -> firebase: <<async>> storePointImage()
firebase --> Service: sendError()
Service --> Api: respuesta del error

deactivate firebase
note right
El punto puede o no contener una imagen.
En en supuesto de que dicho punto no tenga imagen,
no se almacenará la URL.
end note

firebase --> Service: successMsg()
Service -> Service: getStoredImageUrl()
Service -> Service: addNewPoint()
Service -> pod: storeNewPoint()
Service --> Api: mensaje éxito
deactivate Service

Api -> util: convertir a JSON
util --> Api: fichero JSON
Api -> pod: Enviar datos en Blob

activate pod
pod -> pod: Añadir fichero .json
note right
Se envía el punto en un fichero de tipo
.json que contiene toda su información.
end note
pod --> Api: success
deactivate pod

Api --> Personal: Datos actualizados
deactivate Api

deactivate PointView
deactivate Personal

----
