[[section-deployment-view]]


== Deployment View

=== Infrastructure Level 1
:imagesdir: images
image::diagrama_despliegue_L1_v1.svg[]
Motivation::

La aplicación consta de dos partes claramente diferenciadas y separadas, que son lado cliente y lado servidor. En este primer nivel se puede apreciar una arquitectura cliente-servidor, donde el lado del cliente realiza y recibe peticiones HTTP (Mediante dicho protocolo) al lado del servidor, que lo forma una API Rest, la cual realiza consultas contra una base de datos no relacional documental (NoSQL) de MongoDB

Mapping of Building Blocks to Infrastructure::

[cols="1,2", stripes=even]
|===
|Nodo  |Descripción

|Base de datos
| Servidor remoto que almacena y gestiona una base de datos NoSQL en MongoDB.

|webapp
| Nodo que engloba el Front-End de la aplicación, ofreciendo una interfaz de usuario y comunicándose con la api rest para obtener y mostrar los resultados.

|restapi
| Nodo que engloba el Back-End de la aplicación, contiene una API Rest que gestiona las peticiones HTTP recibidas del lado del cliente.

|Proveedor SOLID
| Nodo que representa al proveedor de PODS de SOLID de la empresa Inrupt. Almacenará los PODS personales de los usuario, donde se guardará información privada.

|=== 


=== Infrastructure Level 2
:imagesdir: images
image::diagrama_despliegue_v1.svg[]

Motivation::

El desplieque de la aplicación está orientado para ser integrado en un entorno de integración continua (CI/CD), con el propósito de tener en producción el producto desde el primer día. Para ello, se ha decidido, en base al entorno de pruebas proporcionado, utilizar los contenedores de Docker para empaquetar los respectivos lados de la aplicación (Cliente y servidor). Los contenedores, se albergan en una máquina virtual de Azure.

Quality and/or Performance Features::

El uso de docker para crear un entorno de ejecución virtual, hace que el proceso de despliegue sea más ligero y por ende, se obtenga un mayor rendimiento. Se consigue gracias a trabajar con una imagen de NodeJS (Oficial), que garantiza un entorno estable y listo para ejecutar.

El desarrollo de la webapp utilizando React hace que el tiempo de carga de las páginas sea más rápido (Sin tener en cuenta otros factores, como peticiones a APIs externas como Leaflet).

Por último, la integración de la API de Leaflet facilita el desarrollo del producto, ya que es un proyecto mantenido con frecuencia y de código abierto.

Mapping of Building Blocks to Infrastructure::

[cols="1,2", stripes=even]
|===
|Nodo  |Descripción

| Contenedor Docker
| Utilidad que encapsula un entorno de ejecución de software, incluyendo todas las herramientas de compilación y despliegue necesarias.

|Leaftlet
|API Open Source para integración de mapas en el lado del cliente. Proporciona componentes para React. 

|Servidor Inrupt
| Servicio descentralizado para almacenas los PODS de los usuarios que se registren en él. Cada POD contiene información única de cada usuario.

|Firebase
| Entorno que ofrece un servicio de almacenamiento de recursos multimedia, utilizado para almacenar las imágenes de la aplicación (Véase avatares o imágenes referentes al punto de interés). El servicio se denomina "Firebase Cloud Storage".

|MondoDB Atlas
| Servidor remoto que almacena y gestiona una base de datos NoSQL.

|webapp
| Nodo que engloba el Front-End de la aplicación, ofreciendo una interfaz de usuario y comunicándose con la api rest para obtener y mostrar los resultados.

|restapi
| Nodo que engloba el Back-End de la aplicación, contiene una API Rest que gestiona las peticiones HTTP recibidas del lado del cliente.

| Dispositivo electrónico
| Cualquier dispositivo con acceso a internet, que se conecte al servidor web. Este puede ser un smartphone, tableta, ordenador, consola, etc.

|=== 
