[[section-concepts]]

== Cross-cutting Concepts

=== Domain model

[plantuml, "ModeloDeDominio", png]
----


object Point{
    idPoint: String
    name: String
    description: String
    location: BaseLocation
    owner: User
    reviews: Review[]
    image: String
    isOwner: Boolean
    category: Category
    createdAt: Date
    updatedAt: Date
    friends: Friend[]
}

object Map{
    code: String
    points: Point[]
}

object Review{
    id: String
    title: String
    reviewer: User
    rating: Number
    comment: String
    createdAt: Date
    idPoint: String
}

object User{
    id: String
    name: String
    webId: String
    email: String
    image: String
}

object BaseLocation{
    coords: number[2]
    address: string
    postalCode: number
    city: string
    country : string
}

object Friend{
    ebId : String;
    name : String;
    imgUrl : String;
}

enum Category{
    RESTAURANT
    BAR 
    CAFE
    HOTEL
    GROCERY
    SUPERMARKET
    CINEMA
    SHOP
    MUSEUM
    PARK
    GAS_STATION
    PUBLIC_TRANSPORT
    MONUMENT
    OTHER
    NONE
}

Map*-->Point
Point*-->Review
Point--->User
Review--->User
Point--->BaseLocation
Point--->Category
Point*-->Friend

----
=== Usability

Usaremos react con Typescript. React es un framework que facilita mucho la interactividad con la interfaz de usuario, por lo que es importante para llegar a los usuarios

=== Security

La seguridad de la aplicación es una parte muy importante.
Para que cada persona tenga el control de su información y puedan gestionarla, tendrán cada uno un POD propio.

=== Privacity

El sistema debe mantendrá la privacidad del usuario. Atendiendo a las características de los principios SOLID, toda la información del usuario será almacenada el su propio POD, por lo que no tendrá ninguna vulnerabilidad por tener datos almacenados en una base de datos.

=== Testability

Para el correcto funcionamiento de la aplicacion, para checkear el funcionamiento de los componentes. Es importante unos test para que el usuario tenga la mejor experiencia posible.


